import type { INodeProperties } from 'n8n-workflow';

export const customerOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['customer'] } },
    options: [
      {
        name: 'Create',
        value: 'create',
        description: 'Create a new customer',
        action: 'Create a customer',
        routing: { request: { method: 'POST', url: '/v1/Customers' } },
      },
      {
        name: 'Delete',
        value: 'delete',
        description: 'Delete a customer',
        action: 'Delete a customer',
        routing: { request: { method: 'DELETE', url: '=/v1/Customers/{{$parameter["id"]}}' } },
      },
      {
        name: 'Find',
        value: 'find',
        description: 'Find a customer by email, internal ID, or number',
        action: 'Find a customer',
        routing: { request: { method: 'GET', url: '/v1/Customers/Find' } },
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Get a customer by ID',
        action: 'Get a customer',
        routing: { request: { method: 'GET', url: '=/v1/Customers/{{$parameter["id"]}}' } },
      },
      {
        name: 'Get By Internal ID',
        value: 'getByInternalId',
        description: 'Find a single customer by its internal ID',
        action: 'Get customer by internal ID',
        routing: {
          request: {
            method: 'GET',
            url: '=/v1/Customers/GetByInternalId/{{$parameter["internalId"]}}',
          },
        },
      },
      {
        name: 'Get Contacts',
        value: 'getContacts',
        description: 'Get contacts of a customer',
        action: 'Get customer contacts',
        routing: {
          request: { method: 'GET', url: '=/v1/Customers/{{$parameter["id"]}}/contacts' },
        },
      },
      {
        name: 'List',
        value: 'list',
        description: 'List customers',
        action: 'List customers',
        routing: { request: { method: 'GET', url: '/v1/Customers' } },
      },
      {
        name: 'Update',
        value: 'update',
        description: 'Update a customer',
        action: 'Update a customer',
        routing: { request: { method: 'PUT', url: '=/v1/Customers/{{$parameter["id"]}}' } },
      },
    ],
    default: 'list',
  },
];

export const customerFields: INodeProperties[] = [
  {
    displayName: 'Customer ID',
    name: 'id',
    type: 'number',
    required: true,
    default: 0,
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['get', 'update', 'delete', 'getContacts'],
      },
    },
  },
  {
    displayName: 'Internal ID',
    name: 'internalId',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { resource: ['customer'], operation: ['getByInternalId'] } },
  },
  {
    displayName: 'Find By',
    name: 'findBy',
    type: 'collection',
    placeholder: 'Add Search Field',
    default: {},
    displayOptions: { show: { resource: ['customer'], operation: ['find'] } },
    options: [
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        placeholder: 'name@email.com',
        default: '',
        routing: { request: { qs: { email: '={{$value}}' } } },
      },
      {
        displayName: 'Internal ID',
        name: 'internalId',
        type: 'string',
        default: '',
        routing: { request: { qs: { internalId: '={{$value}}' } } },
      },
      {
        displayName: 'Number',
        name: 'number',
        type: 'string',
        default: '',
        routing: { request: { qs: { number: '={{$value}}' } } },
      },
    ],
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { resource: ['customer'], operation: ['list'] } },
    options: [
      {
        displayName: 'Order By',
        name: 'OrderBy',
        type: 'string',
        default: '',
        routing: { request: { qs: { OrderBy: '={{$value}}' } } },
      },
      {
        displayName: 'Page Index',
        name: 'PageIndex',
        type: 'number',
        default: 0,
        routing: { request: { qs: { PageIndex: '={{$value}}' } } },
      },
      {
        displayName: 'Page Size',
        name: 'PageSize',
        type: 'number',
        default: 50,
        routing: { request: { qs: { PageSize: '={{$value}}' } } },
      },
      {
        displayName: 'Search Query',
        name: 'query',
        type: 'string',
        default: '',
        routing: { request: { qs: { query: '={{$value}}' } } },
      },
    ],
  },
  // Create required fields
  {
    displayName: 'Type',
    name: 'type',
    type: 'options',
    required: true,
    default: 'Business',
    displayOptions: { show: { resource: ['customer'], operation: ['create'] } },
    options: [
      { name: 'Business', value: 'Business' },
      { name: 'Consumer', value: 'Consumer' },
      { name: 'Government', value: 'Government' },
    ],
    routing: { request: { body: { type: '={{$value}}' } } },
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: { show: { resource: ['customer'], operation: ['create', 'update'] } },
    options: [
      {
        displayName: 'Active',
        name: 'active',
        type: 'boolean',
        default: true,
        routing: { request: { body: { active: '={{$value}}' } } },
      },
      {
        displayName: 'Cell Phone',
        name: 'cellPhone',
        type: 'string',
        default: '',
        routing: { request: { body: { cellPhone: '={{$value}}' } } },
      },
      {
        displayName: 'Company Name',
        name: 'companyName',
        type: 'string',
        default: '',
        routing: { request: { body: { companyName: '={{$value}}' } } },
      },
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        placeholder: 'name@email.com',
        default: '',
        routing: { request: { body: { email: '={{$value}}' } } },
      },
      {
        displayName: 'First Name',
        name: 'firstName',
        type: 'string',
        default: '',
        routing: { request: { body: { firstName: '={{$value}}' } } },
      },
      {
        displayName: 'Internal ID',
        name: 'internalId',
        type: 'string',
        default: '',
        routing: { request: { body: { internalId: '={{$value}}' } } },
      },
      {
        displayName: 'Internal Notes',
        name: 'internalNotes',
        type: 'string',
        default: '',
        routing: { request: { body: { internalNotes: '={{$value}}' } } },
      },
      {
        displayName: 'Last Name',
        name: 'lastName',
        type: 'string',
        default: '',
        routing: { request: { body: { lastName: '={{$value}}' } } },
      },
      {
        displayName: 'Number',
        name: 'number',
        type: 'string',
        default: '',
        routing: { request: { body: { number: '={{$value}}' } } },
      },
      {
        displayName: 'Phone',
        name: 'phone',
        type: 'string',
        default: '',
        routing: { request: { body: { phone: '={{$value}}' } } },
      },
      {
        displayName: 'Title',
        name: 'title',
        type: 'string',
        default: '',
        routing: { request: { body: { title: '={{$value}}' } } },
      },
      {
        displayName: 'Type',
        name: 'type',
        type: 'options',
        default: 'Business',
        options: [
          { name: 'Business', value: 'Business' },
          { name: 'Consumer', value: 'Consumer' },
          { name: 'Government', value: 'Government' },
        ],
        routing: { request: { body: { type: '={{$value}}' } } },
      },
    ],
  },
];
